slam_toolbox:
  ros__parameters:
    map_frame: kris_robot1_map
    base_frame: kris_robot1_base_link
    scan_topic: /kris_robot1/scan
    odom_frame: kris_robot1_odom
    namespace: /kris_robot1
    min_laser_range: 0.02
    max_laser_range: 12.0
    use_scan_matching: true