slam_toolbox:
  ros__parameters:
    map_frame: kris_robot4_map
    base_frame: kris_robot4_base_link
    scan_topic: /kris_robot4/scan
    odom_frame: kris_robot4_odom
    namespace: /kris_robot4
    min_laser_range: 0.02
    max_laser_range: 12.0
    use_scan_matching: true